CREATE TABLE IF NOT EXISTS `airports` (
	`id` INT AUTO_INCREMENT PRIMARY KEY,
    `STATE` VARCHAR(2) CHARACTER SET utf8,
    `CODE` VARCHAR(3) CHARACTER SET utf8,
    `CITY` VARCHAR(20) CHARACTER SET utf8,
    `NAME` VARCHAR(75) CHARACTER SET utf8
);
INSERT INTO `airports` (STATE, CODE, CITY, NAME) 
VALUES ('GA','ATL','Atlanta','Hartsfield - Jackson Atlanta International'),
	('TX','DFW','Fort Worth','Dallas-Fort Worth International'),
	('CO','DEN','Denver','Denver International'),
	('CA','LAX','Los Angeles','Los Angeles International'),
	('IL','ORD','Chicago','Chicago O''Hare International'),
	('NY','JFK','New York','John F Kennedy International'),
	('FL','MCO','Orlando','Orlando International'),
	('NV','LAS','Las Vegas','Harry Reid International'),
	('NC','CLT','Charlotte','Charlotte/Douglas International'),
	('FL','MIA','Miami','Miami International'),
	('WA','SEA','Seattle','Seattle-Tacoma International'),
	('NJ','EWR','Newark','Newark Liberty International'),
	('CA','SFO','San Francisco','San Francisco International Airport'),
	('AZ','PHX','Phoenix','Phoenix Sky Harbor International'),
	('TX','IAH','Houston','George Bush Intcntl/Houston'),
	('MA','BOS','Boston','General Edward Lawrence Logan International'),
	('FL','FLL','Fort Lauderdale','Fort Lauderdale/Hollywood International'),
	('MN','MSP','Minneapolis','Minneapolis-St Paul International/Wold-Chamberlain'),
	('NY','LGA','New York','Laguardia'),
	('MI','DTW','Detroit','Detroit Metro Wayne County'),
	('PA','PHL','Philadelphia','Philadelphia International'),
	('UT','SLC','Salt Lake City','Salt Lake City International'),
	('MD','BWI','Baltimore','Baltimore/Washington International Thurgood Marshall'),
	('VA','DCA','Arlington','Ronald Reagan Washington Ntl'),
	('CA','SAN','San Diego','San Diego International'),
	('VA','IAD','Washington','Washington Dulles International'),
	('FL','TPA','Tampa','Tampa International'),
	('TN','BNA','Nashville','Nashville International'),
	('TX','AUS','Austin','Austin-Bergstrom International'),
	('IL','MDW','Chicago','Chicago Midway International'),
	('HI','HNL','Honolulu','Daniel K Inouye International'),
	('TX','DAL','Dallas','Dallas Love Field'),
	('OR','PDX','Portland','Portland International'),
	('MO','STL','St. Louis','St Louis Lambert International'),
	('NC','RDU','Raleigh','Raleigh-Durham International'),
	('TX','HOU','Houston','William P Hobby'),
	('CA','SMF','Sacramento','Sacramento International'),
	('LA','MSY','New Orleans','Louis Armstrong New Orleans International'),
	('CA','SJC','San Jose','Norman Y Mineta San Jose International'),
	('PR','SJU','San Juan','Luis Munoz Marin International'),
	('CA','SNA','Los Angeles','John Wayne/Orange County'),
	('MO','MCI','Kansas City','Kansas City International'),
	('CA','OAK','Oakland','Metro Oakland International'),
	('TX','SAT','San Antonio','San Antonio International'),
	('FL','RSW','Fort Myers','Southwest Florida International'),
	('OH','CLE','Cleveland','Cleveland-Hopkins International'),
	('IN','IND','Indianapolis','Indianapolis International'),
	('PA','PIT','Pittsburgh','Pittsburgh International'),
	('KY','CVG','Cinncinati','Cincinnati/Northern Kentucky International'),
	('OH','CMH','Columbus','John Glenn Columbus International'),
	('FL','PBI','West Palm Beach','Palm Beach International'),
	('HI','OGG','Kahului','Kahului'),
	('FL','JAX','Jacksonville','Jacksonville International'),
	('CA','ONT','Los Angeles','Ontario International'),
	('CA','BUR','Los Angeles','Bob Hope'),
	('CT','BDL','Hartford','Bradley International'),
	('SC','CHS','Charleston','Charleston AFB/International'),
	('WI','MKE','Milwaukee','General Mitchell International'),
	('AK','ANC','Anchorage','Ted Stevens Anchorage International'),
	('NM','ABQ','Albuquerque','Albuquerque International Sunport'),
	('NE','OMA','Omaha','Eppley Airfield'),
	('TN','MEM','Memphis','Memphis International'),
	('VA','RIC','Richmond','Richmond International'),
	('ID','BOI','Boise','Boise Air Trml/Gowen Field'),
	('VA','ORF','Norfolk','Norfolk International'),
	('NY','BUF','Buffalo','Buffalo Niagara International'),
	('KY','SDF','Louisville','Louisville Muhammad Ali International'),
	('NV','RNO','Reno','Reno/Tahoe International'),
	('FL','SRQ','Sarasota','Sarasota/Bradenton International'),
	('OK','OKC','Oklahoma City','Will Rogers World'),
	('HI','KOA','Kailua Kona','Ellison Onizuka Kona International at Keahole'),
	('TX','ELP','El Paso','El Paso International'),
	('WA','GEG','Spokane','Spokane International'),
	('AZ','TUS','Tucson','Tucson International'),
	('GA','SAV','Savannah','Savannah/Hilton Head International'),
	('MI','GRR','Grand Rapids','Gerald R Ford International'),
	('CA','LGB','Long Beach','Long Beach (Daugherty Field)'),
	('HI','LIH','Lihue','Lihue'),
	('RI','PVD','Providence','Rhode Island Tf Green International'),
	('SC','MYR','Myrtle Beach','Myrtle Beach International'),
	('CA','PSP','Palm Springs','Palm Springs International'),
	('OK','TUL','Tulsa','Tulsa International'),
	('IA','DSM','Des Moines','Des Moines International'),
	('AL','BHM','Birmingham','Birmingham-Shuttlesworth International'),
	('FL','SFB','Orlando','Orlando Sanford International'),
	('NY','SYR','Syracuse','Syracuse Hancock International'),
	('TN','TYS','Knoxville','McGhee Tyson'),
	('NY','ALB','Albany','Albany International'),
	('FL','PNS','Pensacola','Pensacola International'),
	('NY','ROC','Rochester','Frederick Douglass/Greater Rochester International'),
	('SC','GSP','Greenville','Greenville Spartanburg International'),
	('FL','PIE','Clearwater','St Pete-Clearwater International'),
	('MT','BZN','Bozeman','Bozeman Yellowstone International'),
	('CA','FAT','Fresno','Fresno Yosemite International'),
	('CO','COS','Colorado Springs','City of Colorado Springs Municipal'),
	('NY','HPN','White Plains','Westchester County'),
	('NC','AVL','Asheville','Asheville Regional'),
	('FL','VPS','Destin','Eglin AFB/Destin-Ft Walton Beach'),
	('ME','PWM','Portland','Portland International Jetport'),
	('AR','LIT','Little Rock','Bill and Hillary Clinton Ntl/Adams Field'),
	('WI','MSN','Madison','Dane County Regional/Truax Field'),
	('AR','XNA','Fayetteville','Northwest Arkansas National'),
	('AR','XNA','Springdale','Northwest Arkansas National'),
	('AZ','IWA','Mesa','Phoenix-Mesa Gateway'),
	('FL','PGD','Punta Gorda','Punta Gorda'),
	('NC','GSO','Greensboro','Piedmont Triad International'),
	('NC','GSO','High Point','Piedmont Triad International'),
	('NC','GSO','Winston-Salem','Piedmont Triad International'),
	('GU','GUM','Tamuning','Guam International'),
	('KS','ICT','Wichita','Wichita Dwight D Eisenhower Ntl'),
	('OR','EUG','Eugene','Mahlon Sweet Field'),
	('FL','ECP','Panama City','Northwest Florida Beaches International'),
	('AL','HSV','Huntsville','Huntsville International-Carl T Jones Field'),
	('VI','STT','Saint Thomas','Cyril E King'),
	('IA','CID','Cedar Rapids','The Eastern Iowa'),
	('TX','MAF','Midland','Midland International Air And Space Port'),
	('HI','ITO','Hilo','Hilo International'),
	('FL','EYW','Key West','Key West International'),
	('KY','LEX','Lexington','Blue Grass'),
	('NC','ILM','Wilmington','Wilmington International'),
	('SD','FSD','Sioux Falls','Joe Foss Field'),
	('PA','MDT','Harrisburg','Harrisburg International'),
	('VT','BTV','Burlington','Patrick Leahy Burlington International'),
	('NH','MHT','Manchester','Manchester Boston Regional'),
	('NY','ISP','Islip','Long Island MacArthur'),
	('CA','SBA','Santa Barbara','Santa Barbara Municipal'),
	('MO','SGF','Springfield','Springfield-Branson Ntl'),
	('MS','JAN','Jackson','Jackson-Medgar Wiley Evers International'),
	('OH','DAY','Dayton','James M Cox Dayton International'),
	('SC','CAE','Columbia','Columbia Metro'),
	('OR','RDM','Redmond','Roberts Field'),
	('AK','FAI','Fairbanks','Fairbanks International'),
	('TX','LBB','Lubbock','Lubbock Preston Smith International'),
	('TX','HRL','Harlingen','Valley International'),
	('ND','FAR','Fargo','Hector International'),
	('TX','MFE','McAllen','McAllen International'),
	('WY','JAC','Jackson','Jackson Hole'),
	('CT','HVN','New Haven','Tweed/New Haven'),
	('TN','CHA','Chattanooga','Lovell Field'),
	('OR','MFR','Medford','Rogue Valley International - Medford'),
	('WI','ATW','Appleton','Appleton International'),
	('MT','MSO','Missoula','Missoula Montana'),
	('MT','GPI','Kalispell','Glacier Park International'),
	('WA','PSC','Tri-Cities','Tri-Cities'),
	('NJ','ACY','Atlantic City','Atlantic City International'),
	('MT','BIL','Billings','Billings Logan International'),
	('PR','BQN','Aguadilla','Rafael Hernandez'),
	('AK','JNU','Juneau','Juneau International'),
	('PA','ABE','Allentown','Lehigh Valley International'),
	('FL','TLH','Tallahassee','Tallahassee International'),
	('UT','PVU','Provo','Provo Municipal'),
	('IN','SBN','South Bend','South Bend International'),
	('TX','AMA','Amarillo','Rick Husband Amarillo International'),
	('IN','FWA','Fort Wayne','Fort Wayne International'),
	('LA','BTR','Baton Rouge','Baton Rouge Metro, Ryan Field'),
	('MS','GPT','Gulfport','Gulfport-Biloxi International'),
	('FL','MLB','Melbourne','Melbourne Orlando International'),
	('ME','BGR','Bangor','Bangor International'),
	('TX','CRP','Corpus Christi','Corpus Christi International'),
	('FL','DAB','Daytona Beach','Daytona Beach International'),
	('MI','TVC','Traverse City','Cherry Capital'),
	('VA','ROA','Roanoke','Roanoke/Blacksburg Regional (Woodrum Field)'),
	('SD','RAP','Rapid City','Rapid City Regional'),
	('OH','CAK','Akron','Akron-Canton Regional'),
	('WI','GRB','Green Bay','Green Bay/Austin Straubel International'),
	('NJ','TTN','Trenton','Trenton Mercer'),
	('CA','SBP','San Luis Obispo','San Luis Obispo County Regional'),
	('CA','STS','Santa Rosa','Charles M Schulz - Sonoma County'),
	('IL','PIA','Peoria','General Downing - Peoria International'),
	('WA','BLI','Bellingham','Bellingham International'),
	('CO','ASE','Aspen','Aspen-Pitkin County/Sardy Field'),
	('LA','SHV','Shreveport','Shreveport Regional'),
	('VA','CHO','Charlottesville','Charlottesville-Albemarle'),
	('WA','PAE','Seattle','Seattle Paine Field International'),
	('MI','FNT','Flint','Bishop International'),
	('GA','AGS','Augusta','Augusta Regional at Bush Field'),
	('AL','MOB','Mobile','Mobile Regional'),
	('FL','GNV','Gainesville','Gainesville Regional'),
	('IL','MLI','Quad Cities','Quad Cities International'),
	('ID','IDA','Idaho Falls','Idaho Falls Regional'),
	('CA','MRY','Monterey','Monterey Regional'),
	('ND','BIS','Bismarck','Bismarck Municipal'),
	('CO','MTJ','Montrose','Montrose Regional'),
	('CO','GJT','Grand Junction','Grand Junction Regional'),
	('VI','STX','Saint Croix','Henry E Rohlsen'),
	('LA','LFT','Lafayette','Lafayette Regional/Paul Fournet Field'),
	('CO','EGE','Eagle','Eagle County Regional'),
	('TN','TRI','Tri-Cities','Tri-Cities'),
	('MP','GSN','Saipan','Francisco C Ada/Saipan International'),
	('CO','DRO','Durango','Durango-La Plata County'),
	('CO','HDN','Hayden','Yampa Valley'),
	('WV','CRW','Charleston','West Virginia International Yeager'),
	('AL','MGM','Montgomery','Montgomery Regional (Dannelly Field)'),
	('MT','GTF','Great Falls','Great Falls International'),
	('LA','AEX','Alexandria','Alexandria International'),
	('TX','BRO','Brownsville','Brownsville/South Padre Island International'),
	('CA','BFL','Bakersfield','Meadows Field'),
	('PA','AVP','Wilkes-Barre','Wilkes-Barre/Scranton International'),
	('PA','AVP','Scranton','Wilkes-Barre/Scranton International'),
	('NC','FAY','Fayetteville','Fayetteville Regional/Grannis Field'),
	('IN','EVV','Evansville','Evansville Regional'),
	('IL','BMI','Bloomington','Central Illinois Regional Airport'),
	('IL','BMI','Normal','Central Illinois Regional Airport'),
	('AK','BET','Bethel','Bethel'),
	('TX','LRD','Laredo','Laredo International'),
	('OH','LCK','Columbus','Rickenbacker International'),
	('AK','KTN','Ketchikan','Ketchikan International'),
	('IL','BLV','St. Louis','Scott AFB/Midamerica St Louis'),
	('ND','MOT','Minot','Minot International'),
	('PR','PSE','Ponce','Mercedita'),
	('NM','SAF','Santa Fe','Santa Fe Regional'),
	('PA','UNV','State College','State College Regional'),
	('MA','ACK','Nantucket','Nantucket Memorial'),
	('UT','SGU','St. George','St George Regional'),
	('NC','OAJ','Jacksonville','Albert J Ellis'),
	('DE','ILG','Wilmington','New Castle'),
	('NE','LNK','Lincoln','Lincoln'),
	('NY','SWF','Newburgh','New York Stewart International'),
	('MN','DLH','Duluth','Duluth International'),
	('IL','RFD','Rockford','Chicago/Rockford International'),
	('NC','JQF','Concord','Concord-Padgett Regional');
